### ISSUE TITLE
Build error after updating @babel/core to >= 7.16.10

### ISSUE THREAD

**Issue by mydea** [javiertury/babel-plugin-transform-import-meta#3]
After updating @babel/core in our app from 7.16.7 to 7.16.10 (and afterwards), I suddenly get this error when building with the following simple config:

Versions:

```json
"@babel/core": "7.17.0",
"@babel/eslint-parser": "~7.17.0",
"@babel/preset-env": "~7.16.11",
```

Babel config used:

```js
import { transformFileAsync } from '@babel/core';

let babelConfig = {
  presets: ['@babel/preset-env'],
  plugins: ['babel-plugin-transform-import-meta'],
  targets: 'node >= 14',
}

let convertedFile = await transformFileAsync(inputFile, babelConfig);
```

Error:

```
TypeError: /my-app/tmp/index.js: ast is not a function
    at PluginPass.Program (file:///my-app/node_modules/babel-plugin-transform-import-meta/lib/index.esm.mjs:40:38)
    at newFn (/my-app/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:177:21)
    at NodePath._call (/my-app/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/my-app/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/my-app/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:100:31)
    at TraversalContext.visitQueue (/my-app/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:103:16)
    at TraversalContext.visitSingle (/my-app/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:77:19)
    at TraversalContext.visit (/my-app/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:131:19)
    at traverseNode (/my-app/node_modules/@babel/core/node_modules/@babel/traverse/lib/traverse-node.js:24:17)
    at traverse (/my-app/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:62:34) {
  code: 'BABEL_TRANSFORM_ERROR'
}
```

After looking at it, it seems that this in `lib/index.esm.mjs`:

```
import template from '@babel/template';

console.log(template); // -->
{
  default: [Function: bound ] {
    smart: [Function (anonymous)] { ast: [Function: ast] },
    statement: [Function (anonymous)] { ast: [Function: ast] },
    statements: [Function (anonymous)] { ast: [Function: ast] },
    expression: [Function (anonymous)] { ast: [Function: ast] },
    program: [Function (anonymous)] { ast: [Function: ast] },
    ast: [Function: ast]
  },
  expression: [Function (anonymous)] { ast: [Function: ast] },
  program: [Function (anonymous)] { ast: [Function: ast] },
  smart: [Function (anonymous)] { ast: [Function: ast] },
  statement: [Function (anonymous)] { ast: [Function: ast] },
  statements: [Function (anonymous)] { ast: [Function: ast] }
}
```

No idea why there is a `default` thing in there, and why `ast` would only be on that `default` property :thinking:

**Comment by javiertury** [comment]
Thank you @mydea for noticing the problem and sending the PR.

Version 2.1.1 has been released and includes your patch :tada:
